sudo: true
language: node_js
node_js:
  - "stable"
  - "6"
  - "4"
install:
  - npm i
  - chmod 644 /etc/profile.d/mirrors.sh
  - source /etc/profile.d/mirrors.sh
after_success:
  - npm run coveralls
