os:
  - osx
sudo: required
language: node_js
node_js:
  - "stable"
  - "6"
  - "4"
install:
  - sudo npm i --unsafe-perm -g mirror-config-china --registry=http://registry.npm.taobao.org
  - sudo chmod 644 /etc/profile.d/mirrors.sh
  - source /etc/profile.d/mirrors.sh
script:
  - node_modules/.bin/eslint lib/*.js
  - node_modules/.bin/istanbul node_modules/.bin/cover node_modules/mocha/bin/_mocha
